### ISSUE TITLE
[docs] Improve clarity of installation for development

### ISSUE THREAD

**Issue by luxaritas** [muctadir/lama#19]
The docker setup is very straight forward (kudos!) but there doesn't seem to be clear documentation beyond software requirements for getting set up for development (what commands am I expected to run? how can I run things with hot reloading? etc).

Related: Following the instructions provided in the README is not sufficient for running tests successfully. You need to install the python requirements via pip to run the backend tests, and even after installing the frontend requirements via npm and setting my chrome binary, no tests were found.

Submitted while reviewing https://github.com/openjournals/joss-reviews/issues/5135

**Comment by JarlJansen123** [comment]
Sorry about the test-cases not working, I thought I fixed it, but I made a typo somewhere. I fixed my typo. Also I added a more detailed explanation on running the test cases. 

For your first point we will provide a detailed description on how to run the tool in a development setting in the next few days. Sorry for the delay.

**Comment by JarlJansen123** [comment]
A detailed description on how to run the tool for development has been added in the readme.
