### ISSUE TITLE
[joss] Additional detail on prior versions

### ISSUE THREAD

**Issue by luxaritas** [muctadir/lama#20]
Currently I'm a little confused about the scope of what is being submitted to JOSS within the context of the previous versions of the application. Namely:
* Is the submission considering this version and the prior two versions as the scope of the contribution?
  * If so, it doesn't look like all prior contributors are included as coauthors, which may suggest a need for revision
  * If not, what is distinct about this version beyond the prior versions? What exactly is the scope of the work done here? What issues or imitations in prior versions were addressed? What is new in this version vs prior versions?  

This may warrant some clarification in the paper itself, though I'm not sure if that's necessary (maybe worth checking with the editor?)

Submitted while reviewing https://github.com/openjournals/joss-reviews/issues/5135

**Comment by muctadir** [comment]
> Is the submission considering this version and the prior two versions as the scope of the contribution?

Current version is the scope of this paper. We mentioned https://github.com/emadpres/labeling-machine as this version is the base for developing https://github.com/muctadir/labeling-machine, which in turn influenced the development of the current version, LaMa.

> * If not, what is distinct about this version beyond the prior versions? What exactly is the scope of the work done here? What issues or imitations in prior versions were addressed? What is new in this version vs prior versions?

There are several improvement in the new version. Project management, user management, multi-labeling just to name a few. We only focused on the key features in the paper as explaining all of them would produce a much longer text. For the same reason, we also did not dive deep into any comparison.

> maybe worth checking with the editor?
I am also not sure entirely. Perhaps this is a good idea. I will leave a note at the review thread.

**Comment by fboehm** [comment]
Thanks for bringing this discussion to my attention, @muctadir. Can you remind me, @muctadir, exactly how you discuss the LaMa predecessors in the paper.md? Please feel free to copy and paste the relevant text of the manuscript in a comment in this thread. Thanks again!

**Comment by muctadir** [comment]
@fboehm, we mention the predecessors in the final paragraph of the __statement of need__ section of [our paper](https://github.com/openjournals/joss-papers/blob/joss.05135/joss.05135/10.21105.joss.05135.pdf).

**Comment by fboehm** [comment]
@muctadir - Thank you for the link. Would it be possible to insert a sentence that lists the limitations of the two previous software packages, emadpres/labeling-machine and muctadir/labeling-machine? Maybe this sentence could go immediately before the sentence "Its key features are described in the following section." 

I don't feel like a detailed comparision with the labeling-machine software is needed for the manuscript, but I would appreciate the addition of this suggested sentence.

**Comment by muctadir** [comment]
@fboehm, thanks for your comment. I will shortly make the necessary changes.

**Comment by luxaritas** [comment]
This is helpful and satisfies my concerns - thanks!
